server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking?useSSL=false&serverTimezone=UTC
    username: root
    password: Priya@1996

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "myverysecretkey12345678901234567890"
  expirationMs: 86400000
razorpay:
  key-id: test_key_123          # dummy value 
  key-secret: test_secret_123   # dummy

