spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:52450/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Priya@1996
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: "thisIsMyJwtSecretKey123"
  expirationMs: 86400000

razorpay:
  key-id: ${RAZORPAY_KEY}
  key-secret: ${RAZORPAY_SECRET}
